### ISSUE TITLE
Unable to execute hassio_install after following wiki guide

### ISSUE THREAD

**Issue by namurdock** [noodlemctwoodle/Hassio#15]
Hey,

Getting the following after successfully cloning the repo, editing the sh files, then executing chmod. Tried executing both on the original file and the copied file... 

> media@Server:/usr/local/bin$ ls

>*docker-compose  easy_install-3.6   miniterm.pyc    pip3         wheel
dockstation     hassio_install.sh  node-red-admin  pip3.6
easy_install    miniterm.py        pip*

>media@Media-Server:/usr/local/bin$ .\hassio_install.sh
*.hassio_install.sh: command not found*

**Comment by noodlemctwoodle** [comment]
Are you using an Intel NUC, as detailed in the guide?

**Comment by namurdock** [comment]
nope.
