### ISSUE TITLE
Unifi Protect MQTT

### ISSUE THREAD

**Issue by johntdyer** [noodlemctwoodle/Hassio#16]
Hey, I am looking to integrate Unifi Protect w/ HA and was I was looking around Github for folks that might be doing anything similar and I stumbled across your repo.  I  specifically found [this](https://github.com/noodlemctwoodle/Hassio/blob/master/configuration.yaml#L169-L175) 

```
# Unifi Protect Motion to MQTT
  - platform: mqtt
    name: Garden Motion
    state_topic: "/camera/motion/back_gate/#"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: motion
```

which seems to imply you've got MQTT working w/ Protect and I am curious if you would care to share how you got this working ?  Thanks

-John

**Comment by johntdyer** [comment]
and I'm an idiot, I found your other repo

**Comment by noodlemctwoodle** [comment]
> and I'm an idiot, I found your other repo

Appologies, I've been out of touch. 

Did you get this working?

**Comment by noodlemctwoodle** [comment]
please come back to me if you still have a problem
